---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(httr)
library(jsonlite)
```

This dashboard displays newest information of inspection for restaurants in New York.

```{r}
## For more informative data display, I download the full nyc_inspections dataset using the code posted on p8105.com rather than using the castrated dataset in p8105.datasets package. (Specifically, to get latitue and longitude information for the restaurants)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```



```{r}
nyc_inspect = 
  nyc_inspections %>%
  distinct() %>% 
  drop_na() %>% 
  separate(inspection_date,into = c("year","other"),4) %>% 
  mutate(year = as.numeric(year),
         long = as.numeric(latitude),
         lat = as.numeric(longitude)) 

rest_new_filter = 
  nyc_inspect %>%
  #Latitude and longitude data seem to be the other way around.
  group_by(camis) %>%
    summarize(year = max(year))

rest_new = left_join(rest_new_filter, nyc_inspect, by = c("camis","year")) %>% 
  select(boro,grade,score,lat,long,dba,cuisine_description) %>% 
  distinct()

```


Column {data-width=550}
-----------------------------------------------------------------------

### An interactive map for restaurants in NYC

```{r}
rest_new %>% 
  mutate(
    text_label = str_c("Name:",dba,"\nGrade:",grade)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long,type = "scatter",mode ="markers",
    color =~grade,text = ~text_label, alpha = 0.5
  )
```

Column {data-width=550}
-----------------------------------------------------------------------

### The top 30 resturant types in NYC

```{r}
rest_popular = rest_new %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n ,.desc = TRUE))

popular_30 = levels(pull(rest_popular,cuisine_description))[1:30]


rest_popular %>% 
  filter(cuisine_description %in%  popular_30) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "viridis")
```

### Top 30 resturant types and their inspection scores

```{r}
rest_new %>% 
  mutate(score = as.numeric(score)) %>% 
  filter(cuisine_description %in%  popular_30) %>% 
  plot_ly(y = ~score, color = ~cuisine_description, type = "box",
          colors = "viridis")
```
